variables:
  CI_IMAGE_BASE: $CI_IMAGE_BASE
  CI_REGISTRY_USER: $CI_REGISTRY_USER
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CI_REGISTRY: $CI_REGISTRY
  BOT_IMAGE_TAG: $CI_IMAGE_BASE/bot:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test
  - deploy

include:
  - .ci/bot.yaml

deploy_job:
  stage: deploy
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY